# Generated by Django 5.2.7 on 2025-11-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('type', models.CharField(max_length=50)),
                ('guest_name', models.CharField(max_length=200)),
                ('method', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Completado', max_length=20)),
                ('reservation_code', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('senores', models.CharField(max_length=200)),
                ('direccion', models.CharField(blank=True, max_length=300, null=True)),
                ('dni', models.CharField(blank=True, max_length=20, null=True)),
                ('concepto', models.TextField(blank=True, null=True)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('son', models.CharField(blank=True, max_length=300, null=True)),
                ('cancelado_fecha', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='cajacobros.payment')),
            ],
            options={
                'db_table': 'receipts',
                'ordering': ['-created_at'],
            },
        ),
    ]
