# Generated by Django 5.2.7 on 2025-12-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Huesped',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal_venta', models.CharField(choices=[('BOOKING', 'Booking'), ('WHATSAPP', 'WhatsApp'), ('RECEPCION', 'Recepción')], default='RECEPCION', max_length=20, verbose_name='Canal de Venta')),
                ('tipo_comprobante', models.CharField(choices=[('BOLETA', 'Boleta'), ('FACTURA', 'Factura')], default='BOLETA', max_length=20, verbose_name='Tipo de Comprobante')),
                ('nombres_apellidos', models.CharField(max_length=200, verbose_name='Nombres y Apellidos Completos')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'CE'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(max_length=20, verbose_name='Número de Documento')),
                ('numero_ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de RUC')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(default='Peruana', max_length=50, verbose_name='Nacionalidad')),
                ('procedencia', models.CharField(max_length=100, verbose_name='Procedencia')),
                ('check_in', models.DateField(verbose_name='Check-in')),
                ('check_out', models.DateField(verbose_name='Check-out')),
                ('tipo_habitacion', models.CharField(choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('MATRIMONIAL', 'Matrimonial'), ('TRIPLE', 'Triple')], max_length=20, verbose_name='Tipo de Habitación')),
                ('numero_habitacion', models.CharField(choices=[('111', '111'), ('112', '112'), ('113', '113'), ('210', '210'), ('211', '211'), ('212', '212'), ('213', '213'), ('214', '214'), ('215', '215'), ('310', '310'), ('311', '311'), ('312', '312'), ('313', '313'), ('314', '314'), ('315', '315')], max_length=3, verbose_name='Número de Habitación')),
                ('tarifa_noche', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tarifa por Noche (S/.)')),
                ('adultos', models.PositiveIntegerField(default=1, verbose_name='Adultos')),
                ('ninos', models.PositiveIntegerField(default=0, verbose_name='Niños')),
                ('metodo_pago', models.CharField(choices=[('EFECTIVO', 'Efectivo'), ('YAPE', 'Yape'), ('TARJETA', 'Tarjeta Débito/Crédito')], default='EFECTIVO', max_length=20, verbose_name='Método de Pago')),
                ('observacion', models.TextField(blank=True, null=True, verbose_name='Observación')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro en Sistema')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Huésped',
                'verbose_name_plural': 'Huéspedes',
                'db_table': 'huespedes',
                'ordering': ['-fecha_registro'],
                'indexes': [models.Index(fields=['numero_documento'], name='huespedes_numero__68f9c1_idx'), models.Index(fields=['check_in'], name='huespedes_check_i_3092ef_idx'), models.Index(fields=['-fecha_registro'], name='huespedes_fecha_r_8ab34d_idx')],
            },
        ),
    ]
