# Generated by Django 5.2.7 on 2025-12-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='condicion',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Condición RUC'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='direccion_completa',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Completa'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='estado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado RUC'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='nombre_o_razon_social',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Nombre o Razón Social'),
        ),
    ]
