# Generated by Django 5.2.7 on 2025-12-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0002_huesped_condicion_huesped_direccion_completa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='check_in',
            field=models.DateField(blank=True, null=True, verbose_name='Check-in'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='check_out',
            field=models.DateField(blank=True, null=True, verbose_name='Check-out'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='nombres_apellidos',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres y Apellidos Completos'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='numero_documento',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='numero_habitacion',
            field=models.CharField(blank=True, choices=[('111', '111'), ('112', '112'), ('113', '113'), ('210', '210'), ('211', '211'), ('212', '212'), ('213', '213'), ('214', '214'), ('215', '215'), ('310', '310'), ('311', '311'), ('312', '312'), ('313', '313'), ('314', '314'), ('315', '315')], max_length=3, null=True, verbose_name='Número de Habitación'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='procedencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Procedencia'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='tarifa_noche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Tarifa por Noche (S/.)'),
        ),
        migrations.AlterField(
            model_name='huesped',
            name='tipo_habitacion',
            field=models.CharField(blank=True, choices=[('SIMPLE', 'Simple'), ('DOBLE', 'Doble'), ('MATRIMONIAL', 'Matrimonial'), ('TRIPLE', 'Triple')], max_length=20, null=True, verbose_name='Tipo de Habitación'),
        ),
    ]
