# Generated by Django 5.2.7 on 2025-12-22 19:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0003_alter_huesped_check_in_alter_huesped_check_out_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='hora_entrada',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Entrada'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='hora_salida',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora de Salida'),
        ),
        migrations.CreateModel(
            name='Acompanante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('DNI', 'DNI'), ('CE', 'CE'), ('PASAPORTE', 'Pasaporte')], default='DNI', max_length=20, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Documento')),
                ('nombres_apellidos', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombres y Apellidos Completos')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('nacionalidad', models.CharField(default='Peruana', max_length=50, verbose_name='Nacionalidad')),
                ('procedencia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Procedencia')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('huesped', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acompanantes', to='huespedes.huesped', verbose_name='Huésped Principal')),
            ],
            options={
                'verbose_name': 'Acompañante',
                'verbose_name_plural': 'Acompañantes',
                'db_table': 'acompanantes',
                'ordering': ['id'],
            },
        ),
    ]
