# Generated by Django 5.2.7 on 2026-01-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0004_huesped_hora_entrada_huesped_hora_salida_acompanante'),
    ]

    operations = [
        migrations.AddField(
            model_name='huesped',
            name='celular',
            field=models.CharField(blank=True, max_length=9, null=True, verbose_name='Número de Celular'),
        ),
        migrations.AddField(
            model_name='huesped',
            name='tipo_desayuno',
            field=models.CharField(choices=[('NINGUNO', 'Ninguno'), ('CONTINENTAL', 'Desayuno Continental'), ('AMERICANO', 'Desayuno Americano')], default='NINGUNO', max_length=20, verbose_name='Tipo de Desayuno'),
        ),
    ]
