# Generated by Django 5.2.7 on 2026-01-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('huespedes', '0005_huesped_celular_huesped_tipo_desayuno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='huesped',
            name='canal_venta',
            field=models.CharField(choices=[('BOOKING', 'Booking'), ('WHATSAPP', 'WhatsApp'), ('RECEPCION', 'Recepción'), ('EXPEDIA', 'Expedia')], default='RECEPCION', max_length=20, verbose_name='Canal de Venta'),
        ),
    ]
