# Generated by Django 5.2.7 on 2025-11-24 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('status', models.CharField(default='Disponible', max_length=50)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor', 'code'],
            },
        ),
    ]
