# Generated by Django 5.2.7 on 2025-11-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_reservation_extras'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Room',
        ),
    ]
