# Generated by Django 5.2.7 on 2025-11-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0004_delete_room'),
        ('reservations', '0004_document_details'),
    ]

    operations = [
    ]
