# Generated by Django 5.2.7 on 2025-11-24 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_companion_document_fields'),
        ('reservations', '0005_merge_0004_delete_room_0004_document_details'),
    ]

    operations = [
    ]
