# Generated by Django 5.2.7 on 2025-11-24 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0006_merge_20251124_1319'),
        ('reservations', '0007_seed_rooms'),
    ]

    operations = [
    ]
