# Generated by Django 5.2.7 on 2025-11-24 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0008_merge_0006_merge_20251124_1319_0007_seed_rooms'),
        ('reservations', '0008_reservation_room'),
    ]

    operations = [
    ]
