# Generated by Django 5.2.7 on 2025-11-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0011_day_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('floor', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(default='Disponible', max_length=50)),
            ],
            options={
                'db_table': 'rooms',
                'ordering': ['floor', 'code'],
            },
        ),
        migrations.AlterField(
            model_name='daynote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
