# Generated by Django 5.2.7 on 2025-11-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0012_room_alter_daynote_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
