# Generated by Django 5.2.7 on 2025-11-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='salary',
            field=models.CharField(blank=True, default='S/', max_length=100, null=True),
        ),
    ]
