# Generated by Django 5.2.7 on 2025-11-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_userprofile_is_activated'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
