# Generated by Django 5.2.7 on 2025-11-05 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_userprofile_profile_photo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_photo_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
