# Generated by Django 5.2.7 on 2025-11-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, verbose_name='Habitación')),
                ('reason', models.TextField(verbose_name='Razón de Bloqueo')),
                ('blocked_until', models.DateField(verbose_name='Bloqueada Hasta')),
                ('blocked_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bloqueada Por')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Habitación Bloqueada',
                'verbose_name_plural': 'Habitaciones Bloqueadas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BriquetteChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha')),
                ('time', models.TimeField(verbose_name='Hora')),
                ('quantity', models.PositiveIntegerField(verbose_name='Cantidad')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Cambio de Briquetas',
                'verbose_name_plural': 'Cambios de Briquetas',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room', models.CharField(max_length=100, verbose_name='Habitación/Área')),
                ('problem', models.TextField(verbose_name='Problema')),
                ('priority', models.CharField(choices=[('Baja', 'Baja'), ('Media', 'Media'), ('Alta', 'Alta')], default='Media', max_length=16, verbose_name='Prioridad')),
                ('technician', models.CharField(blank=True, max_length=100, null=True, verbose_name='Técnico Asignado')),
                ('reported_date', models.DateField(auto_now_add=True, verbose_name='Fecha de Reporte')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Incidencia',
                'verbose_name_plural': 'Incidencias',
                'ordering': ['-reported_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterHeatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operational_status', models.CharField(choices=[('Operativo', 'Operativo'), ('En Mantenimiento', 'En Mantenimiento'), ('Fuera de Servicio', 'Fuera de Servicio')], default='Operativo', max_length=32, verbose_name='Estado Operativo')),
                ('briquettes_this_month', models.PositiveIntegerField(default=0, verbose_name='Briquetas Este Mes')),
                ('last_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Fecha Último Cambio')),
                ('last_maintenance_time', models.TimeField(blank=True, null=True, verbose_name='Hora Último Cambio')),
                ('next_maintenance_date', models.DateField(blank=True, null=True, verbose_name='Fecha Próximo Cambio')),
                ('next_maintenance_time', models.TimeField(blank=True, null=True, verbose_name='Hora Próximo Cambio')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sistema de Agua Caliente',
                'verbose_name_plural': 'Sistema de Agua Caliente',
            },
        ),
    ]
