# Generated by Django 5.2.7 on 2025-11-26 01:53

from django.db import migrations, models, connection


def add_total_column_if_not_exists(apps, schema_editor):
    """Agregar columna total solo si no existe"""
    with connection.cursor() as cursor:
        # Verificar si la columna ya existe
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'lavanderia_laundrystock'
            AND COLUMN_NAME = 'total'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if not exists:
            # Agregar la columna si no existe
            cursor.execute("""
                ALTER TABLE lavanderia_laundrystock 
                ADD COLUMN total INT UNSIGNED NOT NULL DEFAULT 0
            """)


def remove_total_column(apps, schema_editor):
    """Eliminar columna total si existe"""
    with connection.cursor() as cursor:
        cursor.execute("""
            SELECT COUNT(*) 
            FROM information_schema.COLUMNS 
            WHERE TABLE_SCHEMA = DATABASE()
            AND TABLE_NAME = 'lavanderia_laundrystock'
            AND COLUMN_NAME = 'total'
        """)
        exists = cursor.fetchone()[0] > 0
        
        if exists:
            cursor.execute("""
                ALTER TABLE lavanderia_laundrystock 
                DROP COLUMN total
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('lavanderia', '0003_add_funda_column'),
    ]

    operations = [
        # Primero actualizar el estado del modelo (sin tocar la BD)
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_total_column_if_not_exists,
                    reverse_code=remove_total_column
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='laundrystock',
                    name='total',
                    field=models.PositiveIntegerField(default=0, help_text='Total de inventario del hotel'),
                ),
            ],
        ),
    ]
