"""
Django settings for Django_Hotel project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import json
from pathlib import Path
from decouple import config
import firebase_admin
from firebase_admin import credentials
import pymysql
pymysql.install_as_MySQLdb()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='dummy-key-for-build-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default='False', cast=bool)

ALLOWED_HOSTS = [ '*' ]

# CORS settings
CORS_ALLOWED_ORIGINS = [ '*' ]

CORS_ALLOW_CREDENTIALS = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'channels',
    'authentication',
    'messaging',
    'reservations',
    'cajacobros',
    'lavanderia',
    'mantenimiento',
    'dashboard',
    'chatbot',
    'presence',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', 
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'authentication.middleware.FirebaseAuthenticationMiddleware',
]

ROOT_URLCONF = 'Django_Hotel.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Django_Hotel.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Intentar usar DATABASE_URL primero (si está configurado en Seenode)
DATABASE_URL = config('DATABASE_URL', default=None)

if DATABASE_URL:
    # Si DATABASE_URL está configurado, usarlo (puede ser MySQL o PostgreSQL)
    import dj_database_url
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=config('DB_SSL_REQUIRE', default=False, cast=bool)
        )
    }
else:
    # Configuración MySQL directa (desarrollo y producción con MySQL)
    # Valores por defecto para build (se sobrescribirán en producción)
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': config('DB_NAME', default='dummy_db'),
            'USER': config('DB_USER', default='dummy_user'),
            'PASSWORD': config('DB_PASSWORD', default='dummy_password'),
            'HOST': config('DB_HOST', default='localhost'),
            'PORT': config('DB_PORT', default='3306', cast=int),
            'OPTIONS': {
                'charset': 'utf8mb4',
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Lima'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'  # Agregar esta línea

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = config('EMAIL_BACKEND', default='django.core.mail.backends.console.EmailBackend')
EMAIL_HOST = config('EMAIL_HOST', default='localhost')
EMAIL_PORT = config('EMAIL_PORT', default='587', cast=int)
EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
EMAIL_USE_TLS = True

# Lookup API Token
LOOKUP_API_TOKEN = config('LOOKUP_API_TOKEN', default='dummy-token')

# Google Gemini API Key
GEMINI_API_KEY = config('GEMINI_API_KEY', default='dummy-key')

# Ruta al archivo de service account key
FIREBASE_CREDENTIALS_JSON = config('FIREBASE_CREDENTIALS_JSON', default=None)

# Inicializar Firebase solo si las credenciales están disponibles
# Durante el build, esto puede fallar, así que lo hacemos opcional
try:
    if FIREBASE_CREDENTIALS_JSON:
        try:
            # Intentar parsear el JSON
            cred_dict = json.loads(FIREBASE_CREDENTIALS_JSON)
            cred = credentials.Certificate(cred_dict)
            firebase_admin.initialize_app(cred)
            print("Firebase inicializado correctamente desde variable de entorno")
        except (json.JSONDecodeError, ValueError) as e:
            print(f"Error parseando credenciales de Firebase: {e}")
            # Intentar con archivo como fallback
            SERVICE_ACCOUNT_KEY_PATH = os.path.join(BASE_DIR, 'serviceAccountKey.json')
            if os.path.exists(SERVICE_ACCOUNT_KEY_PATH):
                cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
                firebase_admin.initialize_app(cred)
                print("Firebase inicializado desde archivo serviceAccountKey.json")
            else:
                print("Firebase no se pudo inicializar: credenciales no disponibles")
    elif os.path.exists(os.path.join(BASE_DIR, 'serviceAccountKey.json')):
        # Fallback para desarrollo local
        SERVICE_ACCOUNT_KEY_PATH = os.path.join(BASE_DIR, 'serviceAccountKey.json')
        cred = credentials.Certificate(SERVICE_ACCOUNT_KEY_PATH)
        firebase_admin.initialize_app(cred)
        print("Firebase inicializado desde archivo local")
    else:
        print("Firebase no se inicializará: credenciales no encontradas (esto es normal durante el build)")
except Exception as e:
    # Si Firebase falla durante el build, no detener el proceso
    print(f"Advertencia: Firebase no se pudo inicializar: {e}")
    print("La aplicación continuará sin Firebase (esto puede ser normal durante el build)")

# Channels configuration
ASGI_APPLICATION = 'Django_Hotel.asgi.application'

# Channel layers - Redis para producción, InMemory para desarrollo
REDIS_URL = config('REDIS_URL', default=None)

if REDIS_URL:
    # Producción: usar Redis
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                "hosts": [REDIS_URL],
                "capacity": 1500,  # Número máximo de mensajes en cola
                "expiry": 10,  # Tiempo de expiración en segundos
            },
        },
    }
else:
    # Desarrollo: usar InMemory (solo funciona con una instancia)
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }
